### PR TITLE
fixed cookbook list recipe bug and recipe add step x/next s/step command

### LINKED ISSUE #185: [PE-D] No command to view all recipe
If I were to execute the command: *cookbook search recipe k/apple*

And there are no matching recipe, there is no way for me to view all my recipe again!

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: JeremyLoh/ped#3

### PR DESCRIPTION
**Pull request by hans555**
closing #155 
closing #158 

RecipeAddStepCommand now takes Optional<Index> stepIndex rather than Index object
Updated Cookbook search parser
Updated the User guide

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/recipe/RecipeAddStepCommand.java [hunk 1]
```diff
@@ -47,17 +48,24 @@ public CommandResult execute(Model model) throws CommandException {
...
+            if (stepIndex.get().getZeroBased() > targetStepList.asUnmodifiableObservableList().size()) {
+                // ensure the step index is valid
+                throw new CommandException(String.format(MESSAGE_INVALID_STEP_DISPLAYED_INDEX,
+                        RecipeAddCommand.MESSAGE_USAGE));
+            }
+            targetStepList.add(stepIndex.get(), toAdd);
+        } else {
+            newStepIndex = new Index(targetStepList
+                    .asUnmodifiableObservableList().size());
+            targetStepList.add(newStepIndex, toAdd);
```
Comment (gohkh) [inline src/main/java/seedu/address/logic/commands/recipe/RecipeAddStepCommand.java]: Maybe we can have an add method for `UniqueStepList` that adds to the end of the list by default, if no index is provided, like the `add()` method of `java.util.List`. Then we can just call that method here directly.

File: src/main/java/seedu/address/logic/parser/recipe/RecipeAddCommandParser.java [hunk 2]
```diff
@@ -102,11 +103,13 @@ RecipeAddIngredientCommand parseAddIngredient(String args) throws ParseException
      * @throws ParseException if the user input does not conform the expected format
      */
     public RecipeAddStepCommand parseAddStep(String args) throws ParseException {
+        Index recipeIndex;
+        Optional<Index> stepIndex;
+        Step toAdd;
```
Comment (gohkh) [inline src/main/java/seedu/address/logic/parser/recipe/RecipeAddCommandParser.java]: For `toAdd`, I think it's better to initialise it at the bottom like the original version, since there is no point in initialising it so early

File: src/main/java/seedu/address/logic/parser/recipe/RecipeAddCommandParser.java [hunk 3]
```diff
@@ -102,11 +103,13 @@ RecipeAddIngredientCommand parseAddIngredient(String args) throws ParseException
      * @throws ParseException if the user input does not conform the expected format
      */
     public RecipeAddStepCommand parseAddStep(String args) throws ParseException {
+        Index recipeIndex;
+        Optional<Index> stepIndex;
```
Comment (gohkh) [inline src/main/java/seedu/address/logic/parser/recipe/RecipeAddCommandParser.java]: maybe we could directly initialise it to Optional.of(null) so that we just need one if statement without the else, like `if (!stepVariable.equals("next")) {...}`

**Review by gohkh — APPROVED** [review]

File: src/main/java/seedu/address/logic/commands/recipe/RecipeAddStepCommand.java (hunk 1 above)
Comment (hans555) [reply src/main/java/seedu/address/logic/commands/recipe/RecipeAddStepCommand.java]: okay sound good i will implement in now

Comment (hans555) [reply src/main/java/seedu/address/logic/commands/recipe/RecipeAddStepCommand.java]: eh wait its already implemented haha

File: src/main/java/seedu/address/logic/parser/recipe/RecipeAddCommandParser.java (hunk 2 above)
Comment (hans555) [reply src/main/java/seedu/address/logic/parser/recipe/RecipeAddCommandParser.java]: okay i moved them up cause i thought it was kind of messy

File: src/main/java/seedu/address/logic/parser/recipe/RecipeAddCommandParser.java (hunk 3 above)
Comment (hans555) [reply src/main/java/seedu/address/logic/parser/recipe/RecipeAddCommandParser.java]: okay fixed thanks!

**Review by teo-jun-xiong — APPROVED** [review]
